@startuml diagrama_de_caso_de_uso_atualizado
' Thema para um visual mais moderno
!theme vibrant

title Afrodite Calendar - Casos de Uso (Atualizado)

actor "Usuário" as user

rectangle "Sistema Afrodite Calendar" {
  usecase "5.Autenticar-se" as UC_AUTH
  usecase "4.Listar Contatos" as UC_LIST
  usecase "3.Remover Contato" as UC_REMOVE
  usecase "2.Buscar Contato" as UC_SEARCH
  usecase "1.Adicionar Contato" as UC_ADD
}

' Ações diretas do usuário
user -- UC_AUTH
user -- UC_ADD
user -- UC_LIST
user -- UC_SEARCH
user -- UC_REMOVE

' Define que as outras ações dependem da autenticação

@enduml